export const cvsuData = [
  "The library is located between Science Cafe and the College of Agriculture, Food, Environment and Natural Resources (CAFENR). It's also in front of the CvSU Research Building Center.",
  "The Fruit Crop Nursery is placed beside the College of Agriculture, Food, Environment and Natural Resources (CAFENR).",
  "The Cavite Water Testing Laboratory is situated in front of the Fruit Crop Nursery and beside the College of Economics, Management and Development Studies (CEMDS).",
  "Near the College of Economics, Management and Development Studies (CEMDS) and the College of Agriculture, Food, Environment and Natural Resources (CAFENR) and beside the Central Experiment Station, here you can saw the Technology Demonstration Farm.",
  "The location of National Coffee Research, Development and Extension Center (NCRDEC) is near Hostel Tropicana. You can also find it near the area known as 'Japan,' recognizable by its ,distinctive red torii gate.",
  "You can found the Ladies Dormitory (Pink Dorm) near the College of Sports, Physical Education and Recreation (CSPEAR). It's also situated in front of Bahay ng Alumni and beside the Men's Dormitory.",
  "The Men's Dormitory is sited near the College of Sports, Physical Education and Recreation (COPER). It's also situated in front of Bahay ng Alumni and beside the Ladies Dormitory.",
  "You can see Bahay ng Alumni beside the Gymnasium.",
  "The Gymnasium is conveniently settled right next to Bahay ng Alumni and Athletic Field.",
  "The Office of the Student Affairs and Services (OSAS) Building is located near the University Registrar and beside the Gymnasium.",
  "The athletic field (oval) is sited near Gate 1 and directly in front of International House 2.",
  "International House 2 is sited near CvSU Gate 1 and in front of Athletic Field.",
  "Baseball Field is resting beside CvSU Gate 1 and Athletic Field.",
  "Science Highschool Building is currently sited in front of Headquarters Department of Military Science and Tactics ROTC.",
  "The Home Economics Vocational and Technical Education Department (HEVTED) is sited at CvSU Gate 2, in front of the College of Education (CED) Registrar's Office.",
  "The Administration Building is sited in front of the Field/Oval.",
  "The Department of Information Technology (DIT) is placed between College of Engineering and Information Technology (CEIT) and College’s Department of Industrial Engineering and Technology (DIET)",
  "The Department of Industrial Engineering and Technology (DIET) is placed in front of the Department of Computer Electronics and Electrical Engineering (DCEEE).",
  "The Department of Computer Electronics and Electrical Engineering (DCEEE) is sited  in front of the Department of Industrial Engineering and Technology (DIET).",
  "Physical Plant Services is beside the Department of Industrial Engineering and Technology (DIET).",
  "The Agricultural Machinery Laboratory is sited behind the Department of Industrial Engineering and Technology (DIET) and beside the Agricultural Processing Laboratory.",
  "The Agricultural Processing Laboratory is behind the Department of Industrial Engineering and Technology (DIET). It is also situated between the Agricultural Machinery Laboratory and Soil and Water Laboratory.",
  "The Soil and Water Laboratory is sited behind the Department of Industrial Engineering and Technology (DIET) and beside the Agricultural Processing Laboratory.",
  "The Lagoon and Leisure Park is sited in front of Hostel Tropicana.",
  "Hostel Tropicana is near Lagoon and Leisure Park.",
  "Rolle Hall is placed near College of Nursing (CON) and behind Lagoon and Leisure Park.",
  "International Convention Center (ICON) is near Saluysoy and Rolle Hall.",
  "Agritourism Park is sited beside Saluysoy.",
  "The Department of Biological Science is placed between College of Arts and Sciences (CAS) and College of Nursing (CON).",
  "The Museum is placed behind the Library and near Batibot.",
  "The Graduate School and Open learning College is behind the Library.",
  "Infirmary is beside the College of Criminal Justice (CCJ) Building.",
  "Chapel is placed near CvSU Gate 2 and beside the Canteen.",
  "Canteen is in front of Gate 2 and beside the Chapel.",
  "College of Economics, Management and Development Studies (CEMDS) is placed beside CvSU Research Building Center. It is also located in front of the College of Agriculture, Food, Environment and Natural Resources (CAFENR).",
  "The College of Agriculture, Food, Environment and Natural Resources (CAFENR) is sited beside the Library.",
  "The College of Criminal Justice (CCJ) is placed beside the University Infirmary.",
  "The College of Arts and Sciences (CAS) is placed beside the Library and behind the College of Nursing (CON).",
  "The College of Veterinary Medicine and Biomedical Sciences (CVMBS) is sited near Saluysoy, directly in front of the Department of Animal Science Building.",
  "The College of Nursing (CON) is sited near the Lagoon and Leisure Park, beside the Department of Biological Science, and behind the College of Arts and Sciences (CAS).",
  "The College of Education (CED) is near CvSU Gate 2, beside the Administration Building and College of Education Quadrangle.",
  "The College of Sports, Physical Education, and Recreation (CSPEAR) is sited inside the Gymnasium and beside the Office of the Student Affairs and Services (OSAS) Building.",
  "The College of Engineering and Information Technology (CEIT) is near CvSU Gate 2, directly in front of the Administration Building.",
  "The University Mall (U-Mall) is sited near CvSU Gate 3, near 7/11.",
  "The Child Development Center (CDC) is sited near CvSU Gate 2.",
  "The Saluysoy is currently sited beside Agritourism Park.",
];
