export const cvsuData = [
  `The university library is located between Science Cafe and the College of Agriculture, Food, Environment and Natural Resources (CAFENR). It's also in front of the CvSU Research Building Center.`,
  `The Fruit Crop Nursery is located beside the College of Agriculture, Food, Environment and Natural Resources (CAFENR). `,
  `The Cavite Water Testing Laboratory is situated in front of the Fruit Crop Nursery and beside the College of Economics, Management and Development Studies (CEMDS). 	`,
  `The Technology Demonstration Farm is located near the College of Economics, Management and Development Studies (CEMDS) and the College of Agriculture, Food, Environment and Natural Resources (CAFENR), It's also situated beside the Central Experiment Station. `,
  `The National Coffee Research, Development and Extension Center (NCRDEC) is conveniently located near Hostel Tropicana. You can also find it near the area known as "Japan," recognizable by its ,distinctive red torii gate. 	`,
  `The Ladies Dormitory (Pink Dorm) is located near the College of Sports, Physical Education and Recreation (CSPEAR). It's also situated in front of Bahay ng Alumni and beside the Men's Dormitory. `,
  `The Men's Dormitory is conveniently located near the College of Sports, Physical Education and Recreation (COPER). It's also situated in front of Bahay ng Alumni and beside the Ladies Dormitory.`,
  `The Bahay ng Alumni is located beside the Gymnasium.	`,
  `The Gymnasium is conveniently located right next to Bahay ng Alumni and Athletic Field.			`,
  `The Office of the Student Affairs and Services (OSAS) Building is located near the University Registrar and beside the Gymnasium.		`,
  `The athletic field (oval) is located near Gate 1 and directly in front of International House 2.		`,
  `International House 2 is located near CvSU Gate 1 and in front of Athletic Field.		`,
  `Baseball Field is located beside CvSU Gate 1 and Athletic Field.			`,
  `Science Highschool Building is located in front of Headquarters Department of Military Science and Tactics ROTC.		`,
  `The Home Economics Vocational and Technical Education Department (HEVTED) is located at CvSU Gate 2, in front of the College of Education (CED) Registrar's Office.		`,
  `The Administration Building is situated in front of the University Field/Oval.		`,
  `The Department of Information Technology (DIT) is located between College of Engineering and Information Technology (CEIT) and College’s Department of Industrial Engineering and Technology (DIET)	`,
  `The Department of Industrial Engineering and Technology (DIET) is located in front of the Department of Computer Electronics and Electrical Engineering (DCEEE).`,
  `The Department of Computer Electronics and Electrical Engineering (DCEEE) is located  in front of the Department of Industrial Engineering and Technology (DIET).`,
  `Physical Plant Services is situated beside the Department of Industrial Engineering and Technology (DIET).`,
  `The Agricultural Machinery Laboratory is situated behind the Department of Industrial Engineering and Technology (DIET) and beside the Agricultural Processing Laboratory.`,
  `The Agricultural Processing Laboratory is located behind the Department of Industrial Engineering and Technology (DIET). It is also situated between the Agricultural Machinery Laboratory and Soil and Water Laboratory.`,
  `The Soil and Water Laboratory is located behind the Department of Industrial Engineering and Technology (DIET) and beside the Agricultural Processing Laboratory.`,
  `The Lagoon and Leisure Park is located in front of Hostel Tropicana.`,
  `Hostel Tropicana is located near Lagoon and Leisure Park.`,
  `Rolle Hall is located near College of Nursing (CON) and behind Lagoon and Leisure Park.`,
  `International Convention Center (ICON) is located near Saluysoy and Rolle Hall.`,
  `Agritourism Park is located beside Saluysoy.`,
  `The Department of Biological Science is located between College of Arts and Sciences (CAS) and College of Nursing (CON).`,
  `The University Museum is located behind the University Library and near Batibot.`,
  `The Graduate School and Open learning College is located behind the University Library.`,
  `University Infirmary is located beside the College of Criminal Justice (CCJ) Building.`,
  `University Chapel is located near CvSU Gate 2 and beside the University Canteen.`,
  `University Canteen is located in front of Gate 2 and beside the University Chapel.`,
  `College of Economics, Management and Development Studies (CEMDS) is located beside CvSU Research Building Center. It is also located in front of the College of Agriculture, Food, Environment and Natural Resources (CAFENR).`,
  `The College of Agriculture, Food, Environment and Natural Resources (CAFENR) is located beside the University Library.`,
  `The College of Criminal Justice (CCJ) is located beside the University Infirmary.`,
  `The College of Arts and Sciences (CAS) is situated beside the University Library and behind the College of Nursing (CON).`,
  `The College of Veterinary Medicine and Biomedical Sciences (CVMBS) is situated near Saluysoy, directly in front of the Department of Animal Science Building.`,
  `The College of Nursing (CON) is located near the Lagoon and Leisure Park, beside the Department of Biological Science, and behind the College of Arts and Sciences (CAS).`,
  `The College of Education (CED) is situated near CvSU Gate 2, beside the Administration Building and College of Education Quadrangle.`,
  `The College of Sports, Physical Education, and Recreation (CSPEAR) is located inside the Gymnasium and beside the Office of the Student Affairs and Services (OSAS) Building.`,
  `The College of Engineering and Information Technology (CEIT) is located near CvSU Gate 2, directly in front of the Administration Building.`,
  `The University Mall (U-Mall) is situated near CvSU Gate 3, near 7/11.`,
  `The Child Development Center (CDC) is located near CvSU Gate 2.`,
  `The Saluysoy is located beside Agritourism Park.`,
];
